Carry cost is [usually 15% to 30% of the inventory sale price](https://www.zoho.com/inventory/academy/inventory-management/what-is-carrying-cost.html#:~:text=Carrying%20costs%20are%20usually%2015,losing%20money%20over%20unsalable%20items). However, this is typically measured at a annual frequency, so the daily holding cost is more around 0.8% per day. For goods ordered in specifically for Black Friday, the holding cost is likely to be a bit higher due to the time-limited nature of the sales and discounts, so we will increase the daily holding cost to about 2%.
Shortage cost is close to the margin of the good, ie. a lost sale. [50-70% are considered good margins](https://www.unleashedsoftware.com/inventory-accounting-guide/what-is-a-good-profit-margin/).

# We have four scenarios:
- High truck cost, weekly scheduling
- High truck cost, daily scheduling (with a 50% daily premium paid for the luxury)
- Low truck cost, weekly scheduling
- Low truck cost, daily scheduling (with a 50% daily premium paid for the luxury)

Furthermore, we will assume that due to driver constraints, the company has access to only 10 drivers on any day, and hence can hire at most 10 trucks.

Our three items are based on the following high-demand Black Friday items:
- A [new phone launch](https://www.jbhifi.com.au/products/samsung-galaxy-s25-ultra-512gb-titanium-black)
    - Retails for 2200.
    - Which makes the shortage cost roughly 1100.
    - Daily holding cost of 2% is 44.
    - Has a [physical size](https://www.samsung.com/au/smartphones/galaxy-s25-ultra/specs/#:~:text=Physical%20specification,Gear%20Support) of 162.8mm x 77.6mm x 8.2mm, so the box is going to be around 220mm x 130mm x 50mm, meaning this item is around 0.00143 m3, so we could fit around 700 phones per cubic metre.
    - The demand for this item will be relatively high, but due to its high price we will give it a muted demand profile (Good 3).
- A [heavily discounted pair of production recording headphones](https://www.jbhifi.com.au/products/audio-technica-ath-r50x-professional-open-back-headphone)
    - Retails for 400.
    - Which makes the shortage cost about 200.
    - And the daily holding cost 8.
    - Has a [physical size](https://www.amazon.com/Audio-Technica-Professional-Open-Back-Reference-Headphones/dp/B0DTTWF1Z9?th=1) of 100mm x 170mm x 200mm, box size roughly 150mm x 220 mm x 250 mm, which is 0.00825m3, so we could fit about 120 headphones per cubic metre.
    - The demand for this item will be medium, the price point isn't too high and we can assume a large discount is being applied for Black Friday, but it is definitely a more niche product. We will give it the spiky profile (Good 2).
- A [big discount on Samsung's previous model Galaxy Buds](https://www.jbhifi.com.au/products/samsung-galaxy-buds-fe-white)
    - Retails for 200.
    - This would make the shortage cost around 100, but let's say there are significant discounts on this product for Black Friday as its being replaced by the Galaxy Buds 2 in a few months, so the shortage comes down to 50.
    - The daily holding cost would be 4, however because of the heavy discounts applied and upcoming obsolescence, it is unlikely unsold goods will sell. So we will increase the holding cost for this item to 10 to reflect the risk of overstocking.
    - The [box size](https://www.amazon.com.au/Samsung-Galaxy-Buds-FE-SM-R400NZWAEUA/dp/B0CPFH7FBM) is tiny at 97 mm x 85 mm x 42 mm, which is 0.00034629 m3, or about 3K items per cubic metre.


Weekly truck rental data from [here](https://www.budgettrucks.com.au/en/offers/vic/weekly-rates).

1100 for 7 day truck rental with 50m3 space sourced from [here](https://www.hertztrucks.com.au/bookings/choose-vehicle).
- Reasonable to say that daily truck rental cost would be between 100 and 200 depending on demand.
- We are going to assume that not all the capacity of the truck is actually available for just transporting our three items, that would be a ridiculous scenario.
- For instance, we can fit 700 phones into one cubic metre, so the full truck could transport 35K phones.
- Let's make an assumption that these three goods are among 300 items being transported for Black Friday deals, and these items are representative both in price and size. Then we can assume that the average space within each truck used for these items would be 1% of the total capacity, or half a cubic metre.
- Thus we could fit 350 phones per truck, 60 headphones and 1.5K earphones. If we set the truck capacity as the LCM of these values, then we can set the size of each item as:
    - LCM: 10,500
        - 350 phones per truck = size of 30
        - 60 headphones per truck = size of 175
        - 1500 earphones per truck = size of 7

Thus, we end with the following specifications:

Good 1
    - Name: Earphones
    - Size: 7
    - Shortage cost: 50
    - Holding cost: 10

Good 2
    - Name: Headphones
    - Size: 175
    - Shortage cost: 200
    - Holding cost: 8

Good 3
    - Name: Phone
    - Size: 30
    - Shortage cost: 1100
    - Holding cost: 44

Truck
    - Capacity: 10,500
    - Maximum daily trucks: 10
    - Daily cost (low): 100
    - Daily cost (high): 200
    - Premium for daily hire (instead of weekly): 50%

# Results
Scenario 1: High Truck Cost, Weekly Hiring
```
{
  "NumTrucks": 10.0,
  "TruckHire": 14000.0,
  "TransportCosts": 11518.800000000003,
  "ShortageCosts": 0.0,
  "HoldingCosts": 6200.0,
  "TotalCost": 31718.800000000003
}
```
Scenario 2: Low Truck Cost, Weekly Hiring
```
{
  "NumTrucks": 10.0,
  "TruckHire": 7000.0,
  "TransportCosts": 11517.900000000001,
  "ShortageCosts": 0.0,
  "HoldingCosts": 6200.0,
  "TotalCost": 24717.9
}
```
Scenario 3: High Truck Cost, Daily Hiring
```
{
  "NumTrucks": [5.0, 2.0, 2.0, 10.0, 10.0, 4.0, 4.0],
  "TruckHireCosts": 11100.0,
  "TransportCosts": 11654.7,
  "ShortageCosts": 0.0,
  "HoldingCosts": 6464.0,
  "TotalCost": 29218.7
}
```
Scenario 4: Low Truck Cost, Daily Hiring
```
{
  "NumTrucks": [5.0, 2.0, 2.0, 10.0, 10.0, 4.0, 5.0],
  "TruckHireCosts": 5700.0,
  "TransportCosts": 11621.200000000004,
  "ShortageCosts": 0.0,
  "HoldingCosts": 6200.0,
  "TotalCost": 23521.2
}
```

In [533]:
# data import and cleaning
import numpy as np
import json

# "../data/weekly_trucks_low_cost.json"
# "../data/weekly_trucks_high_cost.json"
# "../data/daily_trucks_low_cost.json"
# "../data/daily_trucks_high_cost.json"

with open("../data/daily_trucks_high_cost.json", 'r') as f:
    input_data = json.load(f)

num_warehouses = input_data['num_warehouses']
num_goods = input_data['num_goods']
num_retailers = input_data['num_retailers']
num_periods = input_data['num_periods']
max_trucks = input_data['max_trucks']
truck_capacity = input_data['truck_capacity']
truck_daily_rental_cost = input_data['truck_daily_rental_cost']
truck_rental_period = input_data['truck_rental_period']
shortage_costs = input_data['shortage_costs']
holding_costs = input_data['holding_costs']
good_sizes = input_data['good_sizes']
demand_raw = input_data['demand']
transport_costs_raw = input_data['transportation_costs']


retailer_good_demand = np.ndarray(shape=(num_retailers, num_goods, num_periods))
for retailer, goods_demanded in demand_raw.items():
    for good, demand_schedule  in goods_demanded.items():
        for period, demand in enumerate(demand_schedule):
            retailer_good_demand[int(retailer), int(good), int(period)] = demand

transportation_costs = np.zeros(shape=(num_retailers, num_warehouses, num_goods))
for warehouse, retailer_good_costs  in transport_costs_raw.items():
    for retailer, good_costs in retailer_good_costs.items():
        for good, transport_cost in enumerate(good_costs):
            transportation_costs[int(warehouse), int(retailer), int(good)] = transport_cost

print(f"""Data loaded successfully!
    - num_warehouses: {num_warehouses}
    - num_goods: {num_goods}
    - num_retailers {num_retailers}
    - num_periods: {num_periods}
    - max_trucks: {max_trucks}
    - truck_capacity: {truck_capacity}
    - truck_daily_rental_cost: {truck_daily_rental_cost}
    - truck_rental_period: {truck_rental_period}
    - shortage_costs: {shortage_costs}
    - holding_costs: {holding_costs}
    - good_sizes: {good_sizes}
    - retailer_good_demand:\n {retailer_good_demand}
    - transportation_costs:\n {transportation_costs}
""")

Data loaded successfully!
    - num_warehouses: 5
    - num_goods: 3
    - num_retailers 5
    - num_periods: 7
    - max_trucks: 10
    - truck_capacity: 10500
    - truck_daily_rental_cost: 300
    - truck_rental_period: daily
    - shortage_costs: [50, 200, 1100]
    - holding_costs: [10, 8, 44]
    - good_sizes: [7, 175, 30]
    - retailer_good_demand:
 [[[ 100.   50.   30.   10. 1000.  600.  400.]
  [  50.   20.    0.    0.  200.   10.   20.]
  [  10.    5.    3.    1.  100.   80.   80.]]

 [[ 100.   50.   30.   10. 1000.  600.  400.]
  [  50.   20.    0.    0.  200.   10.   20.]
  [  10.    5.    3.    1.  100.   80.   80.]]

 [[ 100.   50.   30.   10. 1000.  600.  400.]
  [  50.   20.    0.    0.  200.   10.   20.]
  [  10.    5.    3.    1.  100.   80.   80.]]

 [[ 100.   50.   30.   10. 1000.  600.  400.]
  [  50.   20.    0.    0.  200.   10.   20.]
  [  10.    5.    3.    1.  100.   80.   80.]]

 [[ 100.   50.   30.   10. 1000.  600.  400.]
  [  50.   20.    0.    0.  200.  

In [534]:
import gurobipy as gp

m = gp.Model()

warehouses = range(num_warehouses)
goods = range(num_goods)
retailers = range(num_retailers)
periods = range(num_periods)

if truck_rental_period == "weekly":
    num_trucks = m.addVar(lb=0, ub=max_trucks, vtype='I', name="NumTrucks")
elif truck_rental_period == "daily":
    num_trucks = m.addMVar(num_periods, lb=0, ub=max_trucks, vtype='I', name="NumTrucks")
else:
    raise NotImplementedError("Only supports `weekly` or `daily` truck rental.")

truck_allocation = m.addMVar((num_warehouses, num_periods), lb=0, ub=1000, vtype='I', name="TruckAllocation")
transport = m.addMVar((num_warehouses, num_retailers, num_goods, num_periods), lb=0, ub=10000, vtype='I', name="TransportedGoods")
carried_retailer_stock = m.addMVar((num_retailers, num_goods, num_periods+1), lb=0, ub=10000, vtype='I', name="RetailerHeldStock")
short_retailer_stock = m.addMVar((num_retailers, num_goods, num_periods), lb=0, ub=10000, vtype='I', name="RetailerShortStock")

if truck_rental_period == "weekly":
    m.setObjective(
        gp.quicksum(transport[w, r, g, p] * transportation_costs[w, r, g] for w in warehouses for r in retailers for g in goods for p in periods) +
        gp.quicksum(short_retailer_stock[r, g, p] * shortage_costs[g] for g in goods for r in retailers for p in periods) +
        gp.quicksum(carried_retailer_stock[r, g, p] * holding_costs[g] for g in goods for r in retailers for p in range(num_periods+1)) +
        num_trucks * truck_daily_rental_cost * num_periods,
        gp.GRB.MINIMIZE
    )

    # total number of trucks allocated across all warehouses for each period must equal number of trucks hired
    m.addConstrs((gp.quicksum(truck_allocation[w, p] for w in warehouses) == num_trucks for p in periods), name="TruckAllocation")

elif truck_rental_period == "daily":
    m.setObjective(
        gp.quicksum(transport[w, r, g, p] * transportation_costs[w, r, g] for w in warehouses for r in retailers for g in goods for p in periods) +
        gp.quicksum(short_retailer_stock[r, g, p] * shortage_costs[g] for g in goods for r in retailers for p in periods) +
        gp.quicksum(carried_retailer_stock[r, g, p] * holding_costs[g] for g in goods for r in retailers for p in range(num_periods+1)) +
        gp.quicksum(num_trucks[p] for p in periods) * truck_daily_rental_cost,
        gp.GRB.MINIMIZE
    )
    # total number of trucks allocated across all warehouses for each period must equal number of trucks hired
    m.addConstrs((gp.quicksum(truck_allocation[w, p] for w in warehouses) == num_trucks[p] for p in periods), name="TruckAllocation")
else:
    raise NotImplementedError("Only supports `weekly` or `daily` truck rental.")


# total goods sent from a warehouse in each period cannot exceed the capacity of its assigned trucks
m.addConstrs((gp.quicksum(gp.quicksum(transport[w, r, g, p] for r in retailers) * good_sizes[g] for g in goods) <= truck_allocation[w, p] * truck_capacity for w in warehouses for p in periods), name="TruckCapacities")

# first period carried retailer stock equal to 0
m.addConstrs((carried_retailer_stock[r, g, 0] == 0 for r in retailers for g in goods), name="InitialRetailerStock")

# amount of retailer goods carried each period equal to the excess demand in each period
m.addConstrs(
    (
        carried_retailer_stock[r, g, p + 1] == gp.quicksum(transport[w, r, g, p] for w in warehouses) - retailer_good_demand[r, g, p] + carried_retailer_stock[r, g, p] + short_retailer_stock[r, g, p] for r in retailers for g in goods for p in periods
    ), name="RetailerCarryAmounts"
)

# amount of retailer goods short of demand is equal to the unmet demand in each period
m.addConstrs(
    (
        short_retailer_stock[r, g, p] >= retailer_good_demand[r, g, p] - carried_retailer_stock[r, g, p] - gp.quicksum(transport[w, r, g, p] for w in warehouses) for r in retailers for g in goods for p in periods
    ), name="RetailerShortAmounts"
)

m.optimize()

Gurobi Optimizer version 12.0.1 build v12.0.1rc0 (win64 - Windows 11.0 (26100.2))

CPU model: AMD Ryzen 9 7950X 16-Core Processor, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 16 physical cores, 32 logical processors, using up to 32 threads

Optimize a model with 267 rows, 792 columns and 2192 nonzeros
Model fingerprint: 0xe032483b
Variable types: 0 continuous, 792 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+04]
  Objective range  [4e-01, 1e+03]
  Bounds range     [1e+01, 1e+04]
  RHS range        [1e+00, 1e+03]
Presolve removed 125 rows and 37 columns
Presolve time: 0.00s
Presolved: 142 rows, 755 columns, 1400 nonzeros
Variable types: 0 continuous, 755 integer (0 binary)
Found heuristic solution: objective 1.454580e+07
Found heuristic solution: objective 1.351304e+07
Found heuristic solution: objective 2409400.0000
Found heuristic solution: objective 2390000.0000

Root relaxation: objective 2.857810e+04, 192 iterations, 0.00 seconds (0.00 work unit

In [535]:
m.objVal

29218.7

In [536]:
retail_stock = []

for retailer in retailers:
    for good in goods:
        for period in periods:
            retail_stock.append(
                {
                    "Retailer": f"Retail{retailer}",
                    "Good": f"Good{good}",
                    "Period": period,
                    "InitialStock": carried_retailer_stock[retailer][good][period].x.item() + 0.0,
                    "DailySupply": sum(transport[w, retailer, good, period].x + 0.0 for w in warehouses),
                    "Demand": retailer_good_demand[retailer][good][period],
                    "ShortStock": short_retailer_stock[retailer][good][period].x.item() + 0.0,
                }
            )

In [537]:
import pandas as pd

retail_stock_df = pd.DataFrame.from_records(retail_stock)

retail_stock_df

Retailer   Good  Period  InitialStock  DailySupply  Demand  ShortStock
0    Retail0  Good0       0           0.0        100.0   100.0         0.0
1    Retail0  Good0       1           0.0         50.0    50.0         0.0
2    Retail0  Good0       2           0.0         30.0    30.0         0.0
3    Retail0  Good0       3           0.0         10.0    10.0         0.0
4    Retail0  Good0       4           0.0       1000.0  1000.0         0.0
..       ...    ...     ...           ...          ...     ...         ...
100  Retail4  Good2       2           0.0          3.0     3.0         0.0
101  Retail4  Good2       3           0.0          1.0     1.0         0.0
102  Retail4  Good2       4           0.0        100.0   100.0         0.0
103  Retail4  Good2       5           0.0         80.0    80.0         0.0
104  Retail4  Good2       6           0.0         80.0    80.0         0.0

[105 rows x 7 columns]

In [538]:
truck_utilisation = []

for warehouse in warehouses:
    for period in periods:
        truck_utilisation.append(
            {
                'Warehouse': f"Warehouse{warehouse}",
                'Period': period,
                'AssignedTrucks': truck_allocation[warehouse, period].x + 0.0,
                'TotalCapacity': (truck_allocation[warehouse, period].x + 0.0) * truck_capacity,
                'TotalSupplied': sum(transport[warehouse, r, g, period].x * good_sizes[g] + 0.0 for r in retailers for g in goods)
            }
        )

In [539]:
truck_utilisation_df = pd.DataFrame.from_records(truck_utilisation)

truck_utilisation_df['Utilisation'] = (truck_utilisation_df['TotalSupplied'] / truck_utilisation_df['TotalCapacity']).fillna(1.0).apply(lambda x: "{:.2f}".format(x))

truck_utilisation_df

Warehouse  Period  AssignedTrucks  TotalCapacity  TotalSupplied  \
0   Warehouse0       0             2.0        21000.0        19800.0   
1   Warehouse0       1             1.0        10500.0        10425.0   
2   Warehouse0       2             1.0        10500.0         8040.0   
3   Warehouse0       3             5.0        52500.0        52499.0   
4   Warehouse0       4             3.0        31500.0        31460.0   
5   Warehouse0       5             2.0        21000.0        20975.0   
6   Warehouse0       6             2.0        21000.0        20997.0   
7   Warehouse1       0             0.0            0.0            0.0   
8   Warehouse1       1             0.0            0.0            0.0   
9   Warehouse1       2             0.0            0.0            0.0   
10  Warehouse1       3             0.0            0.0            0.0   
11  Warehouse1       4             1.0        10500.0        10495.0   
12  Warehouse1       5             0.0            0.0            0.0   
13  Warehouse1       6             0.0            0.0            0.0   
14  Warehouse2       0             1.0        10500.0        10450.0   
15  Warehouse2       1             1.0        10500.0         9575.0   
16  Warehouse2       2             1.0        10500.0        10435.0   
17  Warehouse2       3             4.0        42000.0        41995.0   
18  Warehouse2       4             2.0        21000.0        21000.0   
19  Warehouse2       5             1.0        10500.0        10500.0   
20  Warehouse2       6             1.0        10500.0        10450.0   
21  Warehouse3       0             1.0        10500.0         9450.0   
22  Warehouse3       1             0.0            0.0            0.0   
23  Warehouse3       2             0.0            0.0            0.0   
24  Warehouse3       3             1.0        10500.0        10481.0   
25  Warehouse3       4             3.0        31500.0        31500.0   
26  Warehouse3       5             1.0        10500.0        10450.0   
27  Warehouse3       6             1.0        10500.0        10478.0   
28  Warehouse4       0             1.0        10500.0         9050.0   
29  Warehouse4       1             0.0            0.0            0.0   
30  Warehouse4       2             0.0            0.0            0.0   
31  Warehouse4       3             0.0            0.0            0.0   
32  Warehouse4       4             1.0        10500.0        10495.0   
33  Warehouse4       5             0.0            0.0            0.0   
34  Warehouse4       6             0.0            0.0            0.0   

   Utilisation  
0         0.94  
1         0.99  
2         0.77  
3         1.00  
4         1.00  
5         1.00  
6         1.00  
7         1.00  
8         1.00  
9         1.00  
10        1.00  
11        1.00  
12        1.00  
13        1.00  
14        1.00  
15        0.91  
16        0.99  
17        1.00  
18        1.00  
19        1.00  
20        1.00  
21        0.90  
22        1.00  
23        1.00  
24        1.00  
25        1.00  
26        1.00  
27        1.00  
28        0.86  
29        1.00  
30        1.00  
31        1.00  
32        1.00  
33        1.00  
34        1.00

In [540]:
total_utilisation = sum(truck_utilisation_df['TotalSupplied']) / sum(truck_utilisation_df['TotalCapacity'])

total_utilisation

0.9806949806949807

In [541]:
if truck_rental_period == "weekly":
    cost_attribution = {
        'NumTrucks': num_trucks.x,
        'TruckHire': num_trucks.x * truck_daily_rental_cost * num_periods,
        'TransportCosts': sum(transport[w, r, g, p].x * transportation_costs[w, r, g] for w in warehouses for r in retailers for g in goods for p in periods),
        'ShortageCosts': sum(short_retailer_stock[r, g, p].x * shortage_costs[g] for g in goods for r in retailers for p in periods),
        'HoldingCosts': sum(carried_retailer_stock[r, g, p].x * holding_costs[g] for g in goods for r in retailers for p in range(num_periods+1)),
        'TotalCost': m.objVal
    }
elif truck_rental_period == "daily":
    cost_attribution = {
        'NumTrucks': list(num_trucks.x + 0.0),
        'TruckHireCosts': sum(num_trucks.x) * truck_daily_rental_cost,
        'TransportCosts': sum(transport[w, r, g, p].x * transportation_costs[w, r, g] + 0.0 for w in warehouses for r in retailers for g in goods for p in periods),
        'ShortageCosts': sum(short_retailer_stock[r, g, p].x * shortage_costs[g] for g in goods for r in retailers for p in periods),
        'HoldingCosts': sum(carried_retailer_stock[r, g, p].x * holding_costs[g] for g in goods for r in retailers for p in range(num_periods+1)),
        'TotalCost': m.objVal
    }
else:
    cost_attribution = {}

print(json.dumps(cost_attribution, indent=2))

{
  "NumTrucks": [
    5.0,
    2.0,
    2.0,
    10.0,
    10.0,
    4.0,
    4.0
  ],
  "TruckHireCosts": 11100.0,
  "TransportCosts": 11654.7,
  "ShortageCosts": 0.0,
  "HoldingCosts": 6464.0,
  "TotalCost": 29218.7
}
